language: node_js
services:
  - rabbitmq
node_js:
  - "0.12"
  - "4"
  - "5"
env:
  - ZEROMQ_VERSION=4.0.4-bpa~precise1
before_install:
  - sudo add-apt-repository ppa:bpaquet/zeromq4-precise -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - sudo apt-get install -y logrotate
  - sudo apt-get install -y libzmq1=${ZEROMQ_VERSION} libzmq-dev=${ZEROMQ_VERSION}
